# Generated by Django 4.0.6 on 2022-07-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_exercise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, height_field=200, null=True, upload_to='images/', width_field=200),
        ),
    ]
