# Generated by Django 4.0.6 on 2022-07-15 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='nameWorkout',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.exercise'),
        ),
    ]
