# Generated by Django 4.0.6 on 2022-07-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_workout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='exercise',
        ),
    ]
