# Generated by Django 4.0.6 on 2022-07-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_workout_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(to='main.exercise'),
        ),
    ]
